development:
  adapter: postgresql
  encoding: unicode
  database: Geocoder_App_development
  host: localhost
  pool: 5
  username: postgres
  password: koko23052020

test:
  adapter: postgresql
  encoding: unicode
  database: Geocoder_App_test
  pool: 5
  username: postgres
  password: koko23052020

production:
  adapter: postgresql
  encoding: unicode
  database: Geocoder_App_production
  pool: 5
  username: postgres
  password: koko23052020

